import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

export default function Home() {

  const [quarters , setQuarters] = useState(0);
  const [dimes , setDimes] = useState(0);
  const [nickels , setNickels] = useState(0);
  const [pennies , setPennies] = useState(0);


  return (
    <>
      <Head>
        <title>Mission 23: Coin Change - VijayAlpha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <nav className="nav__bar">
          <div className="name">
            <Image src="/coin-25.svg" width={50} height={50} alt="coin-25" />
            <h1>Coin Changer</h1>
          </div>
          <div className="">
            <div className="btn">Connect Wallet</div>
          </div>
        </nav>

        <div className="container">
          <div className="">
            <h2>Shardeum Mission 23 - Coin Changer</h2>
            <p>
              This is a Shardeum Mission 23 challenge submission, which uses the
              CoinChanger contract on the Shardeum Sphinx 1.x network. Try to
              add the due amount and your paid amount to calculate the change in
              quarters (25 cents), dimes (10 cents), nickels (5 cents), and
              pennies (1 cent).
            </p>
          </div>
          <div className="inputs">
            <input type="number" name="dueAmount" id="" />
            <input type="number" name="paidAmount" id="" />
          </div>
          <div className="coin-display">
            <h3>Your Change</h3>
            <ul>
              <li>
                <span> {quarters} quarters </span>
                <Image width={150} height={150}  src="/coin-25.svg" alt="" srcset="" />
              </li>
              <li>
                <span> {dimes} dimes </span>
                <Image width={150} height={150}  src="/coin-10.svg" alt="" srcset="" />
              </li>
              <li>
                <span> {nickels} nickels </span>
                <Image width={150} height={150}  src="/coin-5.svg" alt="" srcset="" />
              </li>
              <li>
                <span> {pennies} pennies </span>
                <Image width={150} height={150}  src="/coin-1.svg" alt="" srcset="" />
              </li>
            </ul>
          </div>
        </div>
      </main>
    </>
  );
}
